### ISSUE TITLE
New version message every nth time

### ISSUE THREAD

**Issue by sinnbeck** [permafrost-dev/ray-cli#6]
Every other time I run the phar version, it informs me that there is a new version available :+1: 
![image](https://user-images.githubusercontent.com/13980140/104711380-94633900-5721-11eb-917c-c931a871e4b8.png)

Ubuntu 20.04

**Comment by patinthehat** [comment]
That's odd.  It may be an issue with php's `version_compare()`.  I'll resolve it - thanks for letting me know.

In the mean time, you can run the phar with the `-q` or `--quiet` parameter to suppress it:
`./ray-1.10.0.phar -q 'test'`

**Comment by patinthehat** [comment]
See release [v1.10.1](https://github.com/permafrost-dev/ray-cli/releases/tag/1.10.1). 

Thanks!
